### ISSUE TITLE
missing information about credentials format

### ISSUE THREAD

**Issue by justnils** [devleaks/node-red-contrib-netatmo-homecoach#1]
would be great if you could provide information what kind of credentials are needed and in which form you have to put them into the fields....
without I don't get your node running

**Comment by devleaks** [comment]
Hi,
Sorry for the late reply.
This node is built on the same pattern as other Netatmo nodes. It uses a "Netatmo Config Node" where you need to supply username, password and API key.
Have a look [at this project](https://github.com/guidone/node-red-contrib-netatmo-dashboard).
Best regards.
P.
