### ISSUE TITLE
Missing credential button on NodeRed 2.2.2

### ISSUE THREAD

**Issue by DavidRFI** [devleaks/node-red-contrib-netatmo-homecoach#2]
Hello,

On Node-Red (v2.2.2) I have installed the node-red-contrib-netatmo-homecoach library (v1.0.0) and the node "get home coaches data" does not have the edit button to introduce the credentials in order to connect to netatmo cloud and get the data from the homecoach sensors.

This is very strange because I had installed the same library on Node Red (v1.2.6) in a Rasberry Pi with the same library "node-red-contrib-netatmo-homecoach (v1.0.0)" and it has the button and works properly.

Anybody has experience a similar issue? What can I do to solve this problem?

Missing button on Node Red v2.2.2
![image](https://user-images.githubusercontent.com/74243267/181754450-edf7de09-77d1-4abc-8f7f-f13cacf01ffb.png)

On Node Red v1.2.6 with the button
![image](https://user-images.githubusercontent.com/74243267/181754511-288fa7e9-7551-4812-9b2e-6fcd2893083d.png)

**Comment by devleaks** [comment]
I have no idea. node-red probably changed the way those "accessory" information are supplied.
I'll have a look in the following days.
Thanks for reporting.

**Comment by DavidRFI** [comment]
Hello,

I have updated Node-red to v3.0.1 in other PC and it does not let you install the ***@***.******@***.***> library.

Regards,

David

2022-08-01T13:02:42.618Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict ***@***.******@***.***>
2022-08-01T13:02:44.773Z [err] npm
2022-08-01T13:02:44.773Z [err]  ERR! code EBADENGINE
2022-08-01T13:02:44.784Z [err] npm ERR!
2022-08-01T13:02:44.784Z [err] engine Unsupported engine
2022-08-01T13:02:44.784Z [err] npm ERR! engine Not compatible with your version of node/npm: ***@***.******@***.***>
2022-08-01T13:02:44.784Z [err] npm ERR! notsup Not compatible with your version of node/npm: ***@***.******@***.***>
2022-08-01T13:02:44.784Z [err] npm ERR! notsup Required: {"node":">= 14.0.0"}
2022-08-01T13:02:44.784Z [err] npm ERR!
2022-08-01T13:02:44.784Z [err] notsup Actual:   {"npm":"8.5.1","node":"v12.22.9"}
2022-08-01T13:02:44.785Z [err]
2022-08-01T13:02:44.785Z [err] npm
2022-08-01T13:02:44.785Z [err] ERR! A complete log of this run can be found in:
2022-08-01T13:02:44.785Z [err] npm ERR!     /home/los-laqc/.npm/_logs/2022-08-01T13_02_42_980Z-debug-0.log
2022-08-01T13:02:44.801Z rc=1


De: Pierre M ***@***.***>
Enviado el: viernes, 29 de julio de 2022 17:15
Para: devleaks/node-red-contrib-netatmo-homecoach ***@***.***>
CC: David Ramos ***@***.***>; Author ***@***.***>
Asunto: Re: [devleaks/node-red-contrib-netatmo-homecoach] Missing credential button on NodeRed 2.2.2 (Issue #2)


This message was sent from outside of Gestamp. Please do not click links or open attachments unless you recognise the source of this email and know the content is safe.

I have no idea. node-red probably changed the way those "accessory" information are supplied.
I'll have a look in the following days.
Thanks for reporting.

**Comment by devleaks** [comment]
This module hasn't been update for Node-red 2.X or 3.X.
Please have a look at this [repo](https://github.com/ssadams11/node-red-contrib-netatmo) for a fix. (It faces similar issues when node-red 2.X changed configuration nodes.)
I have no time to bring that modification to this module right now. Sorry.

**Comment by DavidRFI** [comment]
Hello Pierre,

I understand. I made the backwards version to Node-red v1.2.6 and it works… so I will keep in this version

Thank you for your reply and I encourage you to make the effort to upgrade this module! It is fantastic!

Best Regards,

David Ramos.


De: Pierre M ***@***.***>
Enviado el: lunes, 1 de agosto de 2022 16:42
Para: devleaks/node-red-contrib-netatmo-homecoach ***@***.***>
CC: David Ramos ***@***.***>; Author ***@***.***>
Asunto: Re: [devleaks/node-red-contrib-netatmo-homecoach] Missing credential button on NodeRed 2.2.2 (Issue #2)


This message was sent from outside of Gestamp. Please do not click links or open attachments unless you recognise the source of this email and know the content is safe.

This module hasn't been update for Node-red 2.X or 3.X.
Please have a look at this repo<https://github.com/ssadams11/node-red-contrib-netatmo> for a fix. (It faces similar issues when node-red 2.X changed configuration nodes.)
I have no time to bring that modification to this module right now. Sorry.
